CREATE DATABASE ESCOLAR;
-- USAR LA BASE DE DATOS --
USE ESCOLAR;
-- CREACIÓN DE TABLAS --
CREATE TABLE LICENCIATURA (
CVALIC INT UNSIGNED NOT NULL PRIMARY KEY,
NOMBRELIC VARCHAR (100) NOT NULL,
SEMESTRES INT UNSIGNED NOT NULL,
CREDITOSTOTALES INT UNSIGNED NOT NULL
) ENGINE=INNODB;

CREATE TABLE ASIGNATURA (
CVALIC INT UNSIGNED NOT NULL,
CLAVEASIG INT UNSIGNED NOT NULL,
NOMBREASIG VARCHAR (150) NOT NULL,
SEMESTRE INT UNSIGNED NOT NULL,
CREDITOS INT UNSIGNED NOT NULL,
PRIMARY KEY (CVALIC, CLAVEASIG),
FOREIGN KEY (CVALIC) REFERENCES LICENCIATURA(CVALIC)
) ENGINE=INNODB;

CREATE TABLE GRUPO (
NUMGPO INT UNSIGNED NOT NULL PRIMARY KEY,
CUPOMAX INT UNSIGNED NOT NULL,
INSCRITOS INT UNSIGNED NOT NULL
) ENGINE=INNODB;

CREATE TABLE ALUMNO (
NUMCTA INT UNSIGNED NOT NULL PRIMARY KEY,
NOMBREAL VARCHAR (150) NOT NULL,
TELEFONO VARCHAR (10) NOT NULL,
CORREOELECTR VARCHAR (150) NOT NULL,
DOMICILIO VARCHAR (50) NOT NULL,
CODPOS INT UNSIGNED NOT NULL,
NACIONALIDAD VARCHAR (35) NOT NULL,
FECHANAC DATE NOT NULL,
GENERO VARCHAR (10) NOT NULL
) ENGINE=INNODB;

CREATE TABLE MATRICULA (
NUMCTA INT UNSIGNED NOT NULL,
NUMGPO INT UNSIGNED NOT NULL,
PERIODO INT UNSIGNED NOT NULL,
CVALIC INT UNSIGNED NOT NULL,
CLAVEASIG INT UNSIGNED NOT NULL,
CALIFICACION INT UNSIGNED NOT NULL,
PRIMARY KEY (NUMCTA, NUMGPO, PERIODO, CLAVEASIG),
FOREIGN KEY(NUMCTA) REFERENCES ALUMNO(NUMCTA),
FOREIGN KEY (NUMGPO) REFERENCES GRUPO(NUMGPO),
FOREIGN KEY (CVALIC, CLAVEASIG) REFERENCES ASIGNATURA (CVALIC, CLAVEASIG)
) ENGINE= INNODB;

CREATE TABLE DEPARTAMENTO (
CVEDEPTO INT UNSIGNED NOT NULL PRIMARY KEY,
NOMBREDEPTO VARCHAR (40) NOT NULL,
TELEFONODEPTO CHAR (10) NOT NULL,
CORREODEPTO VARCHAR (40) NOT NULL
) ENGINE=INNODB;

CREATE TABLE PROFESOR (
NUMTRAB INT UNSIGNED NOT NULL PRIMARY KEY,
NOMBREPROF VARCHAR (40),
GENEROPROF CHAR (10),
GRADOMAXEST VARCHAR (30) NOT NULL,
AREAESTUDIO VARCHAR (35) NOT NULL,
TELEFONOPROF CHAR (10),
CORREOE VARCHAR (100) NOT NULL,
CVEDEPTO INT UNSIGNED NOT NULL,
FOREIGN KEY (CVEDEPTO) REFERENCES DEPARTAMENTO(CVEDEPTO)
) ENGINE= INNODB;

CREATE TABLE JEFEDEPTO (
NUMTRAB INT UNSIGNED NOT NULL,
NUMPROF INT UNSIGNED NOT NULL,
CVEDEPTO INT UNSIGNED NOT NULL,
FECHAINI DATE NOT NULL,
FECHAFINAL DATE NOT NULL,
PRIMARY KEY (NUMTRAB, CVEDEPTO),
FOREIGN KEY (NUMTRAB) REFERENCES PROFESOR (NUMTRAB),
FOREIGN KEY (CVEDEPTO) REFERENCES DEPARTAMENTO (CVEDEPTO)
) ENGINE= INNODB;

CREATE TABLE ENSENIA (
NUMPROF INT UNSIGNED NOT NULL,
NUMGPO INT UNSIGNED NOT NULL,
CVELIC INT UNSIGNED NOT NULL,
CVEASIG INT UNSIGNED NOT NULL,
PERIODO INT UNSIGNED NOT NULL,
PRIMARY KEY (NUMPROF, NUMGPO, CVELIC, CVEASIG, PERIODO),
FOREIGN KEY (NUMPROF) REFERENCES PROFESOR (NUMTRAB),
FOREIGN KEY (NUMGPO) REFERENCES GRUPO(NUMGPO),
FOREIGN KEY (CVELIC, CVEASIG) REFERENCES ASIGNATURA (CVALIC, CLAVEASIG)
) ENGINE=INNODB;

CREATE TABLE AULA (
IDAULA INT NOT NULL PRIMARY KEY,
TIPOAULA VARCHAR (35) NOT NULL,
CUPOMAX INT UNSIGNED NOT NULL
) ENGINE=INNODB;

CREATE TABLE ASIGNA (
IDHORARIO INT UNSIGNED NOT NULL,
PERIODO INT UNSIGNED NOT NULL,
IDAULA INT NOT NULL,
NUMGPO INT UNSIGNED NOT NULL,
DIA1 VARCHAR (3) NOT NULL,
HORAINI_1 CHAR (5) NOT NULL,
HORAFIN_1 CHAR (5) NOT NULL,
DIA2 VARCHAR (3) NOT NULL,
HORAINI_2 VARCHAR (5) NOT NULL,
HORAFIN_2 VARCHAR (5) NOT NULL,
DIA3 VARCHAR (3) NOT NULL,
HORAINI_3 VARCHAR (5) NOT NULL,
HORAFIN_3 VARCHAR (5) NOT NULL,
PRIMARY KEY (IDHORARIO, PERIODO),
FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA),
FOREIGN KEY (NUMGPO) REFERENCES GRUPO(NUMGPO)
) ENGINE=INNODB;

